### ISSUE TITLE
cannot assign unit "mysql/0" to machine 0/lxd/0: adding storage to lxd container not supported

### ISSUE THREAD

**Issue by nobuto-m** [canonical/mysql-operator#408]
## Steps to reproduce

1. `juju deploy mysql --channel 8.0/edge --base ubuntu@22.04 --to lxd` on MAAS provider

## Expected behavior

A LXD container is assigned on top of one physical host

## Actual behavior

cannot assign unit "mysql/0" to machine 0/lxd/0: adding storage to lxd container not supported

```
$ juju export-bundle
default-base: ubuntu@22.04/stable
applications:
  mysql:
    charm: mysql
    channel: 8.0/edge
    revision: 210
    num_units: 1
    to:
    - ""
    constraints: arch=amd64
    storage:
      database: rootfs,1,1024M
```

```
$ juju status 
Model       Controller       Cloud/Region  Version  SLA          Timestamp
mysql-test  maas-controller  maas/default  3.4.0    unsupported  04:59:29Z

App    Version  Status  Scale  Charm  Channel   Rev  Exposed  Message
mysql           error     0/1  mysql  8.0/edge  210  no       cannot assign unit "mysql/0" to machine 0/lxd/0: adding storage to lxd container not supported

Unit     Workload  Agent  Machine  Public address  Ports  Message
mysql/0  error     lost                                   cannot assign unit "mysql/0" to machine 0/lxd/0: adding storage to lxd container not supported

Machine  State    Address          Inst id              Base          AZ       Message
0        started  192.168.151.115  fun-tick             ubuntu@22.04  default  Deployed
0/lxd/0  started  192.168.151.116  juju-e92865-0-lxd-0  ubuntu@22.04  default  Container started    
```

## Versions

Operating system: Ubuntu 22.04 LTS

Juju CLI: 3.4.0-genericlinux-amd64

Juju agent: 3.4.0

Charm revision: mysql  8.0/edge  210

LXD: 5.0.3

## Log output

Juju debug log: 

N/A - since it's a metadata issue

**Comment by nobuto-m** [comment]
I haven't looked into the detail, but it seems to be working now.

```
$ juju status
Model  Controller       Cloud/Region  Version  SLA          Timestamp
test   maas-controller  maas/default  3.6.3    unsupported  09:39:01Z

App    Version          Status  Scale  Charm  Channel   Rev  Exposed  Message
mysql  8.0.41-0ubun...  active      1  mysql  8.0/edge  362  no       

Unit      Workload  Agent  Machine  Public address   Ports           Message
mysql/0*  active    idle   0/lxd/0  192.168.151.106  3306,33060/tcp  Primary

Machine  State    Address          Inst id              Base          AZ       Message
0        started  192.168.151.105  machine-2            ubuntu@22.04  default  Deployed
0/lxd/0  started  192.168.151.106  juju-d90788-0-lxd-0  ubuntu@22.04  default  Container started
```

```yaml
$ juju storage --format yaml
storage:
  database/0:
    kind: filesystem
    life: alive
    status:
      current: attached
      since: 28 Feb 2025 09:14:56Z
    persistent: false
    attachments:
      units:
        mysql/0:
          machine: 0/lxd/0
          location: /var/snap/charmed-mysql/common
          life: alive
filesystems:
  0/lxd/0/0:
    provider-id: 0/lxd/0/0
    storage: database/0
    attachments:
      machines:
        0/lxd/0:
          mount-point: /var/snap/charmed-mysql/common
          read-only: false
          life: alive
      units:
        mysql/0:
          machine: 0/lxd/0
          location: /var/snap/charmed-mysql/common
          life: alive
    pool: rootfs
    size: 64197
    life: alive
    status:
      current: attached
      since: 28 Feb 2025 09:14:56Z
```

```
$ juju exec -u mysql/0 lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0 63.7M  1 loop 
loop1    7:1    0 89.4M  1 loop 
loop2    7:2    0 44.4M  1 loop 
sda      8:0    0   64G  0 disk 
├─sda1   8:1    0    1M  0 part 
└─sda2   8:2    0   64G  0 part /var/snap/charmed-mysql/common
                                /
sdb      8:16   0   16G  0 disk 
sdc      8:32   0   16G  0 disk 
sdd      8:48   0   16G  0 disk 
```
